name = "struere-tool-executor"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "unsafe_eval"]

[vars]

[env.production]
routes = [
  { pattern = "tool-executor.struere.dev", custom_domain = true }
]
